{
 "title": "Invincible Voice Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of conversations per account (cumulative, we should fix this)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (le) (storage_conversations_per_account_bucket)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of accounts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "max(storage_accounts)" }
   ]
  },
  {
   "title": "Number of conversations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "max(storage_conversations)" }
   ]
  },
  {
   "title": "Concurrent STT sessions ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "max(redis_stt_locks)" }
   ]
  },
  {
   "title": "Concurrent TTS sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "max(redis_tts_locks)" }
   ]
  },
  {
   "title": "Number of messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "max(storage_messages)" }
   ]
  }
 ]
}